# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  database: curso_ruby
  host: localhost
  port: 5432
  username: postgres
  password: 1980216
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: curso_ruby

test:
  <<: *default
  database: curso_ruby

production:
  <<: *default
  database: desafio_ror_production
  username: desafio_ror
  password: <%= ENV["DESAFIO_ROR_DATABASE_PASSWORD"] %>
